-- 코드를 입력하세요
SELECT
    RI.FOOD_TYPE
    , RI.REST_ID
    , RI.REST_NAME
    , RI.FAVORITES
FROM
    REST_INFO RI
WHERE
    (FOOD_TYPE, FAVORITES) IN 
    (SELECT
        FOOD_TYPE
        , MAX(FAVORITES)
     FROM
        REST_INFO
     GROUP BY
        FOOD_TYPE)
ORDER BY
    RI.FOOD_TYPE DESC;