-- 코드를 작성해주세요
SELECT 
    II.ITEM_ID
    , II.ITEM_NAME
    , II.RARITY
FROM
    ITEM_INFO II
    JOIN ITEM_TREE IT
    ON II.ITEM_ID = IT.ITEM_ID
    JOIN ITEM_INFO III
    ON IT.PARENT_ITEM_ID = III.ITEM_ID
WHERE
    III.RARITY = 'RARE'
ORDER BY 
    II.ITEM_ID DESC;