-- 코드를 작성해주세요
SELECT 
    ED1.ID
    , ED1.GENOTYPE
    , ED2.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA ED1
    INNER JOIN ECOLI_DATA ED2
    ON ED1.PARENT_ID = ED2.ID
WHERE -- 비트 연산 후 부모 형질 ED2과 같은지 확인
    ED1.GENOTYPE & ED2.GENOTYPE = ED2.GENOTYPE
ORDER BY 
    ED1.ID ASC;
